### PR TITLE
CHERRY-PICK: optimize editBox fit system window

### PR DESCRIPTION
**Pull request by PPpro**
re:  https://github.com/cocos-creator/3d-tasks/issues/4026

sync pr from : https://github.com/cocos-creator/cocos2d-x-lite/pull/2630

### CODE REVIEW

**Comment by PPpro** [comment]
requested a review from @minggo

**Comment by minggo** [comment]
该 PR 包含了多余的内容。

**Comment by PPpro** [comment]
不小心 push 了，已经去掉了多余的 commit

**Comment by minggo** [comment]
提交到 3d-gfx 分支吧。

**Pull request closed without merging**
