### PR TITLE
fix android project name in system setting app

### PR DESCRIPTION
**Pull request by nzlov**
show "libcocos2dx" when  android:label="libcocos2dx"

### CODE REVIEW

**Comment by natural-law** [comment]
@nzlov Why remove the android:label of the library project? I think the config In the AndroidManifest.xml of game project(e.g. `templates/js-template-default/frameworks/proj.android/AndroidManifest.xml`) will cover the config in the library.

**Comment by nzlov** [comment]
thx.Forgive my English.
After compile and install a display name of `libcocos`, not a project name. But the package name will be displayed after you delete, I think it should be replaced in the name of the creator of the project.

**Comment by natural-law** [comment]
@nzlov I will test it. Thanks for your feedback & contribution.

**Comment by nzlov** [comment]
@natural-law thx.

**Comment by natural-law** [comment]
I'm sorry that I have not reproduce the problem. I test it both on `MI 4LTE(Android 6.0.1)` & `MI 2S(Android 4.1.1)`.

**Comment by nzlov** [comment]
@natural-law Sorry, these days the computer a little problem. You see `Android System` `settings - app` display names.

**Comment by natural-law** [comment]
> You see Android System settings - app display names.

Yep, That's what I tested. The result looks like this:
image

**Comment by nzlov** [comment]
Woo. Why am I so?
pastedgraphic-1
```
Creator 1.2.2-beta2
OSX10.10.5
XCODE 7.2.1
Google Android 6.0.1 ElementalX Kernel
```

**Comment by natural-law** [comment]
Yep, I've reproduced this problem. But the right solution should be like [this](https://github.com/cocos-creator/cocos2d-x-lite/pull/340).

@nzlov Thanks for your feedback. Please close this PR.

**Pull request closed without merging**
