### PR TITLE
3dgfx JNI improve thread safe

### PR DESCRIPTION
**Pull request by PatriceJiang**
task: https://github.com/cocos-creator/2d-tasks/issues/2819 

ref: https://github.com/cocos2d/cocos2d-x/pull/18189

### CODE REVIEW

**Comment by minggo** [comment]
Now `jni env` is not attach to current thread, it is cached, so i think this PR can not make it thread safe thoroughly.

**Comment by minggo** [comment]
I don't know how this PR resolve thread safe. It seems there is not difference compared to current implementation.

**Comment by PatriceJiang** [comment]
The issue is described here https://github.com/cocos2d/cocos2d-x/issues/16581

**Comment by minggo** [comment]
Oh, thanks. I forgot to fix it.

**Pull request merged**
