### PR TITLE
remove proj.android files for creator2.0

### PR DESCRIPTION
**Pull request by drelaptop**
## creator should do some corresponding changes

1. remove ant modify script when build to avoid the errors below

ant-remote

2. Don't copy build files for proj.android, like:

ant-remove-file

3. others I don't know about ant and proj.android if existed

@jareguo please check this work

### CODE REVIEW

**Comment by jareguo** [comment]
LGTM

**Comment by drelaptop** [comment]
@jareguo thanks for review.

I can modify the cocos2d-x-lite and cocos-console for this work, but I know little for Creator Editor. So works mentioned above about the Editor need to be done by creator guys. I hope you can assign someone to do.

**Comment by jareguo** [comment]
Sure, issues relative to the building can ask @wuzhiming for help.

**Comment by drelaptop** [comment]
Thanks for share this. I think I should new a issue in fireball repo for the Editor works. Native part works was finished after the console sub-module updated.

**Comment by drelaptop** [comment]
@minggo please merge

this PR do those works:

1. remove proj.android directory in link and default template
2. sync sub-module cocos-console, including ant build script removed

**Comment by drelaptop** [comment]
### __Don't Merge !!!__ Until creator 2.0 beta was packed finish.

**Pull request merged**
